### PR TITLE
Merge image2 branch into image

### PR DESCRIPTION
**Pull request by LukasBanana**

### CODE REVIEW

**Comment by LukasBanana** [comment]
Thank you @BearishSun for your contribution, the image output looks already good and I appreciate your coding style.

Since I never worked a lot with `RWTexture` objects, I currently have not much to test this, and that's also why I don't work on the image load/store translation right now.

I hope you understand that I always do a couple of formatting and naming-convention changes,
but I try to minimize such changes.

**Comment by BearishSun** [comment]
Feel free to modify it all you want, I'm glad to have it merged. And I'm far from fully understanding the project so I'm sure there are things I'm not doing exactly right., I only managed to get this far because you keep it really well organized, it's easy to get around.

I wrote and analyzed a considerable amount of shaders for game engine renderers, both HLSL and GLSL, and have a good idea of what's needed in practice, so I'm focusing on implementing those features. I ran some larger shaders of mine through xsc and currently the `RWTexture` objects are the only thing that was obviously missing. 

After I'm done with the features I'll be running xsc over all my shaders because I'm at a point it's becoming really unfeasible to maintain HLSL and GLSL versions of shaders for my BansheeEngine project. Hopefully this will bring xsc closer to being production ready as well, by having some meaty shaders ran through it on a regular basis.

The main thing that remains regarding `RWTexture` is support for atomic operations, as different methods are used when they're executed over 'image' types (atomicAdd -> imageAtomicAdd). 

Also I'd like to change `RWBuffer` behavior to map to `imageBuffer` and `Buffer` to map to `samplerBuffer`, unless you have a specific reason for keeping them as they are now.

**Comment by LukasBanana** [comment]
Sounds great.

There was no special reason, to always map `Buffer` and `RWBuffer` to GLSL `buffer`, but it was the first and easiest way to do it. If you think `imageBuffer` and `samplerBuffer` are more reasonable for these types, changing it might be a good idea.

But what about `RWStructuredBuffer`? I think for this type `buffer` is the only option to keep the struct inside it.

EDIT:
Maybe it's good to make this optional for the user, to specifiy how things should be mapped, if there are several options.

**Comment by BearishSun** [comment]
`RWStructuredBuffer` (and `StructuredBuffer`) should stay as `buffer`, I agree, as I don't believe any other buffer type in GLSL supports array of structures of arbitrary length. Other buffer types can stay mapped to it as well (I haven't found a use for them in practice anyway). The two buffer types I mentioned are almost direct analogues of each other in HLSL/GLSL so I think it makes sense to translate them as such. 

It could be also be optional sure, but I think the user can just choose to use `RWStructuredBuffer` instead of `RWBuffer`, or `StructuredBuffer` instead of `Buffer`.

**Comment by LukasBanana** [comment]
That's a good point, and I think it's better to reduce the amount of compiler options instead of adding unnecessary complexity.

BTW:
For a better understanding of the overall AST structure, I started with a [brief document](https://github.com/LukasBanana/XShaderCompiler/blob/master/docu/DevNotes.md), describing one of the most complex parts of the AST: object identifiers (constisting of several AST classes).
I began with this document, because I started to struggle with the AST structure myself, due to parsing problems that still exist.
So I'll make a big refactoring about `VarIdent`, `FunctionCallExpr`, `VarAccessExpr`, and `ArrayAccessExpr` in the next days.

Maybe this document might also be helpfull for you, although it describes the planed structure and does not reflect the exact current state!

**Pull request merged**
