### PR TITLE
- Added hacky return code implementation.

### PR DESCRIPTION
**Pull request by rgthomas**
Hey Lukas,

Here's the quick and dirty return code implementation I made. I'm sure it misses other failure cases. I'd be happy to make a better implementation of the return codes if you have time to give me some general feedback about what to look for and any sort of stylistic or architectural guidelines you'd like me to follow.

Thanks for the great tool!

Robert

### CODE REVIEW

**Comment by LukasBanana** [comment]
Thanks for your contribution, it's nice to see this tool being used for practical projects.
For contributions, I like to point out, that I don't use tabs in the code (only in the test shaders),
since they look differently depending on the IDE settings. Instead I use 4 spaces.

If you could change your **tabs to spaces**, replace the boolean **pointer** `bool*` into a boolean **reference** `bool&`, and then **squash** your two commits, then I'd like to merge it into the master branch.

**Review by LukasBanana — COMMENTED** [review]
General approach looks good. Simple but effective.
What should be changed:
- Tabs into 4 spaces.
- Boolean pointer `bool* succeeded` into boolean reference `bool& succeeded`.

**Comment by rgthomas** [comment]
I update my fork with the changes but I'm actually not sure how to update the pull request. All my past experience use git used branches for pull requests and that was about three years ago, so I'm a bit rusty :)

**Comment by rgthomas** [comment]
Oh never mind, it looks like it's been auto-updated.

**Comment by LukasBanana** [comment]
I moved this functionality into the new `CompileStatus` struct of the shell state (i.e. `ShellState` struct), that contains the number of succeeded and failed compilations (see [bfe0990](https://github.com/LukasBanana/XShaderCompiler/commit/bfe0990700909645e89aaede5e0dba9c416d3853)).
This, however, does not work with presettings because it has its own internal state.
But as far as I can see it, you are not using the presettings anyway.

**Pull request merged**
