### PR TITLE
Fix some OpenGL Extensions versions.

### PR DESCRIPTION
**Pull request by v7medz**
Fix SeparateShaders Extension (now adds the extension in Fragment shader).

### CODE REVIEW

**Comment by LukasBanana** [comment]
Thanks for your contribution. However, could you please remove the changes in `.gitignore` because it seems to be an individual case for your platform environment.
The rest looks good.

**Comment by LukasBanana** [comment]
Ok thanks, now please **squash** your two commits, then I'll merge it.

**Comment by v7medz** [comment]
@LukasBanana Can't you merge it without squashing (I dunno how to us git properly I use visual studio GitHub plugin.)

**Comment by LukasBanana** [comment]
I know that's annoying, but I'd like to have commits that undo something being squashed.
Shouldn't be too difficult (take a look at [stackoverflow](https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed)).

**Comment by LukasBanana** [comment]
Well then, I'll squash it myself when I have time for it. Maybe this weekend or next week.

**Comment by v7medz** [comment]
Sorry, but I don't understand git and how to execute commands inside visual studio, also I was very busy in real life and working on my engine.
I hope you understand and thanks.

**Comment by LukasBanana** [comment]
I merged your commits with [66af376](https://github.com/LukasBanana/XShaderCompiler/commit/66af376c26d5bc8f8d3560c826cea8f4c21bacc8) manually.

**Pull request closed without merging**
