### PR TITLE
Added reflection code for shader uniforms

### PR DESCRIPTION
**Pull request by zillemarco**
I've added reflection code to handle shader uniforms since I have this need.
One thing I didn't handle is the uniform binding location since, looking at the code, it seems it isn't handled by the compiler.

### CODE REVIEW

**Comment by LukasBanana** [comment]
Thanks for your contribution.

There is an [`.editorconfig`](https://github.com/LukasBanana/XShaderCompiler/blob/master/.editorconfig) file to ensure consistent code formatting and indentation style.
If your IDE does not support it (I think it's only natively supported by Visual Studio 2017) please make sure you use 4 spaces instead of tabs.

Please adjust your formatting and then squash the commit.

Thanks and kind regards,
Lukas

**Comment by zillemarco** [comment]
Ok no problems :)

**Comment by LukasBanana** [comment]
Do you still want this pull request to be merged into the master branch?
Because I'm still waiting for your formatting adjustment, i.e. conversion of tabs into 4 spaces.

**Comment by zillemarco** [comment]
Yes of course. Sorry for the delay but I had some issues at work and at the university. Just give me 2-3 hours and I'll make the changes.

**Comment by LukasBanana** [comment]
No problem, I was just wondering if there was a misunderstanding.
I could have changed it quickly, but it would undo your contribution.

**Comment by zillemarco** [comment]
Well, I didn't do it for the credits :) If you need to make the changes right know you can do it of course, otherwise I'll make them in 2 or 3 hours :)

**Comment by LukasBanana** [comment]
If it's all right, you'll do it.
Greetings,
Lukas

**Comment by zillemarco** [comment]
Done. It should be fine now :) Thanks for your understanding :)

**Comment by LukasBanana** [comment]
Thanks for your contribution.

If you make a new commit where you add something to the public structs like `ReflectionData`,
please be so good to also update the C and C# wrappers,
e.g. [`XscReflectionData`](https://github.com/LukasBanana/XShaderCompiler/blob/master/inc/XscC/ReflectionC.h#L125) and [`XscCompiler.ReflectionData`](https://github.com/LukasBanana/XShaderCompiler/blob/master/src/Wrapper/CSharp/XscCSharp.cpp#L293).
I'll do it this time.

Greetings,
Lukas

**Comment by zillemarco** [comment]
My apologies, since I never used the C and C# bindings it didn't even cross my mind. I'll keep it in mind for the next time :)

**Pull request merged**
